### ISSUE TITLE
运行时出错

### ISSUE THREAD

**Issue by woshiwangyilei** [tomwillow/SmartCharsetConverter#1]
![2023-05-06_145038](https://user-images.githubusercontent.com/112162946/236608206-1071c597-edca-45cb-99b2-0e7c80a9863b.png)
不明白怎么解决

**Comment by tomwillow** [comment]
这是程序bug导致的。已经在v0.4版修复。

下载地址：
https://github.com/tomwillow/SmartCharsetConverter/releases/tag/v0.4

**Comment by woshiwangyilei** [comment]
感谢！
