### ISSUE TITLE
支持新国标GB1803-2022嘛

### ISSUE THREAD

**Issue by huashao1123** [tomwillow/SmartCharsetConverter#12]

**Comment by tomwillow** [comment]
你好，这个程序内核用的是icu库做转换。我查了一下，icu库从73.2开始支持GB18030-2022。

SmartCharsetConverter现在最新的v0.9.1版用的是icu74，所以应该是支持GB18030-2022的。

我自己在win10 x64平台下测试时，UNICODE表示的emoji符号，转换到GB18030编码时显示是正常的，互转也是正常的。表明本程序至少是支持GB18030中4字节编码部分的。
