### ISSUE TITLE
如何使用命令行模式

### ISSUE THREAD

**Issue by SimHapQ** [tomwillow/SmartCharsetConverter#5]
win10

直接使用图形界面无异常.

调用程序 --help ，无回显。
"智能编码集转换器 v0.7 by Tom Willow.exe" --help

./SmartCharsetConverter --help
'.' 不是内部或外部命令，也不是可运行的程序

**Comment by tomwillow** [comment]
bug已确认。
等我查明原因修复了再回复你。

**Comment by tomwillow** [comment]
bug已经在v0.71版修复。

https://github.com/tomwillow/SmartCharsetConverter/releases/tag/v0.71
