### ISSUE TITLE
转码字幕，添加带有视频文件夹，程序闪退

### ISSUE THREAD

**Issue by Yun7Chen** [tomwillow/SmartCharsetConverter#6]
即便指定了后缀，但点击添加文件夹，并选中带视频文件夹后，程序就闪退了，估计是先扫描文件再过滤后缀，因文件过大出错，猜的。希望能优化一下操作逻辑。

另，是否能优化下界面，简要说明下指定后缀等支持的格式，比如是否可以指定多个后缀、间隔符等，这个好象文档中也没说明。

智能判断，是个好设计，批量转换时，确实不可能每个文件都是相同编码，一对一定向不科学。

**Comment by tomwillow** [comment]
1. 大文件闪退的问题已修复。
2. 支持的后缀已说明，并且增加了多种后缀填写格式。

已经更新到v0.72版。
https://github.com/tomwillow/SmartCharsetConverter/releases/tag/v0.72

谢谢！
