### ISSUE TITLE
Locale Support

### ISSUE THREAD

**Issue by c-sanchez** [tomwillow/SmartCharsetConverter#7]
After searching for several days, I luckily found SmartCharsetConverter, which is exactly what I was looking for :D
The only bad thing about the program so far is that it is not available at least in English.

Please add support to be able to translate the program to any language.

**Comment by tomwillow** [comment]
Thank you for your issue! 😊

I'll do my best to develop this function as soon as possible. However, I can't guarantee a deadline because I spend most of my free time caring for my baby daughter. 🍼

**Comment by c-sanchez** [comment]
No rush, take as much time as you need.

Leave me a message here when you have it, I will be glad to help translating the program into Spanish :)

**Comment by tomwillow** [comment]
Oh, my guess is real. I saw your github repositories which have some content of Spanish yestoday, so I guess you maybe from Spain.

Thank you to your future contributions!

**Comment by tomwillow** [comment]
Multi-language supporting is added~
And I added an English README, the step of the method of adding language pack was in `README-en.md - Add language pack`.

p.s. If you find any mistake of English expression, I will be glad to fix it:)

**Comment by c-sanchez** [comment]
Hello! wow, that was fast haha.
Attached is the Spanish translation :D
[Spanish.json](https://github.com/tomwillow/SmartCharsetConverter/files/13815491/Spanish.json)

**Comment by tomwillow** [comment]
I have built and release new version :[version 0.81](https://github.com/tomwillow/SmartCharsetConverter/releases/tag/v0.81)

Your translation has been embed in it~

Thanks for your supporting😊
