### ISSUE TITLE
Graphical Interface Redesign

### ISSUE THREAD

**Issue by c-sanchez** [tomwillow/SmartCharsetConverter#8]
The graphical interface I think can be improved by reorganizing all the elements in a better way.

The two most important points are:

1. The file list is the main element, where we see the important information.
Currently it is only visible as a secondary element of the window and we can only see a very limited amount of files without scrolling.

2. Although options are important, they should not be the main element.
One idea is to better organize everything on one side of the window.

**This is the current GUI design**
![](https://i.ibb.co/fxQR5gT/Smart-Charset-Converter-gui01.jpg)

**A simple mockup I made, using RisohEditor**
![](https://i.ibb.co/HYMJW6G/Smart-Charset-Converter-mockup01.jpg)

What do you think? :)

**Comment by tomwillow** [comment]
Thanks for your advice! 🙌

I agree that your GUI design is better!👍 
I will implement it in the next major version.

**Comment by tomwillow** [comment]
I have modified GUI as your design last night, and I plan to release new version after I realized the function of multi-language supporting.

I saw the TextEncoder's interface, it's a good reference~

**Comment by tomwillow** [comment]
Version 0.8 is published: [v0.8](https://github.com/tomwillow/SmartCharsetConverter/releases/tag/v0.8)

The interface of v0.8 is based on your design.

Minimize / maximize / resizing was recorded into TODO Lists, maybe I will implement these function at some time of future:)

**Comment by c-sanchez** [comment]
Great! Now the interface is much nicer.
I also like how you have added to change the program language in a simple and fast way :D
